Habit details and edits
CMPUT301F21T23/HabitTracker pull request #187
Opened 2021-11-28 22:44 UTC by PaoVal

Hello All. This PR will resolve #160 

#160, mostly includes UI modifications to the habit list, habit detailed view list, habit event edit view. 
I provided some much needed user feedback, improved the UI/UX for the detail and edit view. added colour, reduced the amount of text, added icons instead, etc...

This PR resolves #3, #12, #25

#3 - is the user story regarding adding habits. The add habit UI was slightly modified and improved. 
#12 - is the user story regarding habit editing. Amongst many other improvements, the fields are now pre-filled.
#25 - is the user story regarding the habit list. The habit list was edited and finalized with this PR no further changes should occur.

@NickSNFK I think your progress stuff should still be working but I'd appreciate if you could take a look to give it the final go-ahead.

2021-11-28 22:45 UTC, PaoVal commented
(Please ignore my commits where I cited issue 120. That was a mistake and I meant to say #160

2021-11-28 22:52 UTC, NickSNFK commented on code/HabitTracker/app/src/main/java/com/example/habittracker/activities/HabitEditActivity.java
> +
Javadoc Police.

2021-11-28 22:57 UTC, NickSNFK requested changes
Everything looks good to me. Tested and everything works as intended.
See my comment on the JavaDoc for file: HabitEditActivity

2021-11-28 23:02 UTC, PaoVal commented on code/HabitTracker/app/src/main/java/com/example/habittracker/activities/HabitEditActivity.java
> +
Thanks!!!

2021-11-29 02:44 UTC, NickSNFK approved these changes

2021-11-29 02:46 UTC, merged